#!/usr/bin/env bash

# Stop on error
set -e

# Source env file
source .env

# Create gateway network
hasGatewayNetwork=$(docker network ls | grep gateway | wc -l)
if [ "$hasGatewayNetwork" == "0" ]; then
  echo "Create gateway network:"
  docker network create \
    --driver=bridge \
    --attachable \
    --internal=false \
    gateway
fi

BASE_CONTAINERS=${BASE_CONTAINERS:-"proxy whoami1 whoami2"}

first_arg=${1:-up}
second_arg=${2:-}

echo "arg1:$first_arg"
echo "arg2:$second_arg"

if [ "$first_arg" == "up" ]; then

  # Launch traefik by default
  docker-compose -f docker-compose.yml -p traefik up -d

  case "${second_arg}" in
      base)           docker-compose -f docker-compose2.yml -f docker-compose3.yml -p ${COMPOSE_PROJECT_NAME:-apps} up -d "${@:3}" ${BASE_CONTAINERS} ;;
      *)              docker-compose -f docker-compose2.yml -f docker-compose3.yml -p ${COMPOSE_PROJECT_NAME:-apps} up -d "${@:2}" ;;
  esac

  exit

fi

docker-compose -f docker-compose.yml -f docker-compose2.yml -f docker-compose3.yml "$@"
