version: '3.7'

services:

  whoami1:
    image: containous/whoami
    ports:
      - "8040:80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami1.entrypoints=web"
    networks:
      - default
      - whoami1

#  app:
#    image: nginx
#    ports:
#      - "8443:443"
#      - "8081:80"
#    labels:
#      - "traefik.enable=true"
#      - "traefik.http.routers.app.entrypoints=websecure"
#    volumes:
#      - ./nginx/index.html:/var/www/html/public/index.html
#      - ./nginx/index2.html:/var/www/html/public/index2.html
#      - ./nginx/app.conf:/etc/nginx/conf.d/app.conf
#      - ./nginx/app2.conf:/etc/nginx/conf.d/default.conf
#      - ./nginx/certs:/etc/nginx/certs

#  api:
#    image: nginx
#    labels:
#      - "traefik.enable=true"
#      - "traefik.http.routers.api.entrypoints=web"
#    volumes:
#      - ./nginx/index.html:/var/www/html/public/index.html
#      - ./nginx/index2.html:/var/www/html/public/index2.html
#      - ./nginx/app.conf:/etc/nginx/conf.d/app.conf
#      - ./nginx/app2.conf:/etc/nginx/conf.d/default.conf
#      - ./nginx/certs:/etc/nginx/certs

networks:
  default:
    external:
      name: gateway
#    ipam:
#      driver: default
#      config:
#        - subnet: ${DOCKER_SUBNET}
  whoami1:
    internal: true
