version: '3.7'

services:

  # src: https://blog.silarhi.fr/docker-compose-traefik-https/
  proxy:
    image: traefik:v2.2
    ports:
      - "8080:8080"
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
#      - ./proxy/traefik_http_https.yml:/etc/traefik/traefik.yml
      - ./proxy/traefik_http_to_https.yml:/etc/traefik/traefik.yml
      - ./proxy/certs/example.crt:/etc/traefik/example.crt
      - ./proxy/certs/example.key:/etc/traefik/example.key

  whoami1:
    image: containous/whoami
    ports:
      - "8040:80"

  whoami2:
    image: containous/whoami
    ports:
      - "8041:80"

  app:
    image: nginx
    ports:
      - "8443:443"
      - "8081:80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.entrypoints=websecure"
    volumes:
      - ./nginx/index.html:/var/www/html/public/index.html
      - ./nginx/index2.html:/var/www/html/public/index2.html
      - ./nginx/app.conf:/etc/nginx/conf.d/app.conf
      - ./nginx/app2.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certs:/etc/nginx/certs

  api:
    image: nginx
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.entrypoints=web"
    volumes:
      - ./nginx/index.html:/var/www/html/public/index.html
      - ./nginx/index2.html:/var/www/html/public/index2.html
      - ./nginx/app.conf:/etc/nginx/conf.d/app.conf
      - ./nginx/app2.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certs:/etc/nginx/certs

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: ${DOCKER_SUBNET}
